services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql


  etl:
    build: .
    environment:
      API_URL: "https://jsonplaceholder.typicode.com/posts"
      DB_HOST: "db"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - db
    volumes:
      - .:/app

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DB_HOST: "db"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: